/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbItem: typeof import('./src/components/admins/breadcrumb/BreadcrumbItem.vue')['default']
    FooterItem: typeof import('./src/components/users/footer/FooterItem.vue')['default']
    HomeTitleItem: typeof import('./src/components/users/home_title/HomeTitleItem.vue')['default']
    HotNotice: typeof import('./src/components/users/hot_notice/HotNotice.vue')['default']
    InputForm: typeof import('./src/components/input/InputForm.vue')['default']
    LoadingItem: typeof import('./src/components/users/loading/LoadingItem.vue')['default']
    ModalConfirm: typeof import('./src/components/admins/modal/ModalConfirm.vue')['default']
    NavHeader: typeof import('./src/components/users/nav_header/NavHeader.vue')['default']
    NavHeaderItem: typeof import('./src/components/admins/nav_header/NavHeaderItem.vue')['default']
    PaginateItem: typeof import('./src/components/users/paginate/PaginateItem.vue')['default']
    ParticleItem: typeof import('./src/components/users/particle/ParticleItem.vue')['default']
    ProfileItem: typeof import('./src/components/users/profile/ProfileItem.vue')['default']
    RightScrollbar: typeof import('./src/components/users/right_scrollbar/RightScrollbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderItem: typeof import('./src/components/admins/sider/SiderItem.vue')['default']
    SkillHeader: typeof import('./src/components/users/skill_header/SkillHeader.vue')['default']
    TimeLine: typeof import('./src/components/users/time_line/TimeLine.vue')['default']
  }
}
